---
title: "Teaching"
---

## University of Evansville

**Principles of Macroeconomics (ECON 101)**: Fall 2024, Spring 2025, Fall 2025

*Catalog Description:* Macroeconomics is the branch of economics that studies the domestic economic system as a whole and its interaction with foreign economies. This course focuses on the behavior of the aggregate economy as it pertains to the determination of national income, production, level of employment, general price level, and trace flows. Particular attention is devoted to fiscal policy and monetary policy and their respective impact on the economic system. Satisfies a general education requirement in human behavior and society. [(Syllabus)](/assets/documents/taylor_ue_econ101_syllabus_f24.pdf)

**Principles of Microeconomics (ECON 102)**: Spring 2025

*Catalog Description:* Markets are among the oldest social institutions known to man. Microeconomics is a branch of economics that studies the dynamics of individual markets and prices. Focuses on the behavior of producers and consumers and the interdependence in the market process. Pays particular attention to the structure and evolution of competitive markets. Satisfies a general education requirement in human behavior and society.

**Regression Analysis (ECON 300)**: Fall 2024

*Catalog Description:* Second course in applied statistics for students in economics and other social sciences, business administration, mathematics, or natural sciences. Topics include simple and multiple regression analysis, extensions of the classical regression model, and problems associated with forecasting. Assigned work exposes students to problems from a wide range of applications. This course includes introduction to econometric software and experiments involving a variety of real world data sets. [(Syllabus)](/assets/documents/taylor_ue_econ300_syllabus_f24.pdf)

**Intermediate Macroeconomics (ECON 346)**: Fall 2025

*Catalog Description:* Macroeconomics is the study of the economy as a whole. Course analyzes the factors determining the growth in income, changes in prices, and the rate of unemployment. As appropriate, the course makes use of models suited to the long run and the short run and models of both open and closed economies.

## George Mason University

**Economics of Developing Areas (ECON 360)**: Fall 2021

*Catalog Description:* Economic growth characteristic of developing countries. Economic development, obstacles to development, policies, and planning. [(Syllabus)](/assets/documents/taylor_gmu_econ360_syllabus.pdf)

**International Economic Policy (ECON 385)**: Spring 2022

*Catalog Description:* Introduces economic way of thinking on trade and international finance. Presents historical and current information on consequences of trade and protectionism. [(Syllabus)](/assets/documents/taylor_gmu_econ385_syllabus.pdf)
